# -*- coding: utf-8 -*-
"""인공지능과 데이터과학 과제2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PfVH13sztPOZpqYjHc-drwhJYqxdG1Bx
"""

# 한글 폰트 설치 및 설정
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

import matplotlib.pyplot as plt
import seaborn as sns

import pandas as pd

file_1 = '/content/1학기 탐구질문 만들기.xlsx'
file_2 = '/content/2학기 탐구질문 만들기.xlsx'

try:
    df_1 = pd.read_excel(file_1)
    df_2 = pd.read_excel(file_2)

    print('1학기 탐구질문 만들기.xlsx Head:')
    print(df_1.head())
    print('\n2학기 탐구질문 만들기.xlsx Head:')
    print(df_2.head())

except FileNotFoundError as e:
    print(f"파일을 찾을 수 없습니다: {e}")
except Exception as e:
    print(f"파일을 읽는 도중 오류가 발생했습니다: {e}")

df_1['탐구질문 평균점수'] = df_1[['탐구질문 만들기1', '탐구질문 만들기2', '탐구질문 만들기3', '탐구질문 만들기4']].mean(axis=1)
display(df_1.head())

df_2['탐구질문 평균점수'] = df_2[['탐구질문 만들기1', '탐구질문 만들기2', '탐구질문 만들기3', '탐구질문 만들기4']].mean(axis=1)
display(df_2.head())

import statsmodels.api as sm
from sklearn.preprocessing import StandardScaler

# Define independent (X) and dependent (y) variables
X = df_1[['탐구질문 평균점수']]
y = df_1['총괄평가']

# Standardize the variables
scaler_X = StandardScaler()
X_scaled = scaler_X.fit_transform(X)
X_scaled_df = pd.DataFrame(X_scaled, columns=X.columns)

scaler_y = StandardScaler()
y_scaled = scaler_y.fit_transform(y.values.reshape(-1, 1))
y_scaled_df = pd.DataFrame(y_scaled, columns=['총괄평가_scaled'])

# Add a constant (intercept) to the independent variable for statsmodels
X_scaled_with_const = sm.add_constant(X_scaled_df)

# Fit the OLS (Ordinary Least Squares) model
model = sm.OLS(y_scaled_df, X_scaled_with_const)
results = model.fit()

# Print the summary of the regression results
print("\n회귀 분석 결과 (표준화된 계수):")
print(results.summary())

"""### 회귀 분석 결과 설명

위 결과는 '1학기 탐구질문 평균점수'가 '총괄평가'에 미치는 영향을 회귀 분석한 요약입니다. 표준화된 계수를 확인하기 위해 모든 변수를 표준화한 후 모델을 적합했습니다.

주요 내용은 다음과 같습니다:

*   **R-squared (결정계수):** 이 값이 높을수록 모델이 종속 변수(총괄평가)의 변동성을 잘 설명한다고 볼 수 있습니다.
*   **Const (상수항):** 표준화된 모델에서는 상수항이 0에 가까울 것으로 예상됩니다.
*   **탐구질문 평균점수 (표준화된 계수):** 이 계수는 독립 변수(탐구질문 평균점수)가 1 표준편차 증가할 때 종속 변수(총괄평가)가 몇 표준편차 증가(또는 감소)하는지를 나타냅니다. 이 값이 클수록 해당 독립 변수가 종속 변수에 미치는 영향이 크다고 해석할 수 있습니다.
*   **P-value (P>|t|):** 이 값은 해당 계수가 통계적으로 유의미한지 여부를 나타냅니다. 일반적으로 0.05보다 작으면 통계적으로 유의미하다고 판단합니다.
"""

import statsmodels.api as sm
from sklearn.preprocessing import StandardScaler

# Define independent (X) and dependent (y) variables for df_2
X_2 = df_2[['탐구질문 평균점수']]
y_2 = df_2['총괄평가']

# Standardize the variables for df_2
scaler_X_2 = StandardScaler()
X_scaled_2 = scaler_X_2.fit_transform(X_2)
X_scaled_df_2 = pd.DataFrame(X_scaled_2, columns=X_2.columns)

scaler_y_2 = StandardScaler()
y_scaled_2 = scaler_y_2.fit_transform(y_2.values.reshape(-1, 1))
y_scaled_df_2 = pd.DataFrame(y_scaled_2, columns=['총괄평가_scaled_2'])

# Add a constant (intercept) to the independent variable for statsmodels
X_scaled_with_const_2 = sm.add_constant(X_scaled_df_2)

# Fit the OLS (Ordinary Least Squares) model for df_2
model_2 = sm.OLS(y_scaled_df_2, X_scaled_with_const_2)
results_2 = model_2.fit()

# Print the summary of the regression results for df_2
print("\n2학기 회귀 분석 결과 (표준화된 계수):")
print(results_2.summary())

"""### 2학기 회귀 분석 결과 설명

위 결과는 '2학기 탐구질문 평균점수'가 '총괄평가'에 미치는 영향을 회귀 분석한 요약입니다. 표준화된 계수를 확인하기 위해 모든 변수를 표준화한 후 모델을 적합했습니다.

주요 내용은 다음과 같습니다:

*   **R-squared (결정계수):** 이 값이 높을수록 모델이 종속 변수(총괄평가)의 변동성을 잘 설명한다고 볼 수 있습니다.
*   **Const (상수항):** 표준화된 모델에서는 상수항이 0에 가까울 것으로 예상됩니다.
*   **탐구질문 평균점수 (표준화된 계수):** 이 계수는 독립 변수(탐구질문 평균점수)가 1 표준편차 증가할 때 종속 변수(총괄평가)가 몇 표준편차 증가(또는 감소)하는지를 나타냅니다. 이 값이 클수록 해당 독립 변수가 종속 변수에 미치는 영향이 크다고 해석할 수 있습니다.
*   **P-value (P>|t|):** 이 값은 해당 계수가 통계적으로 유의미한지 여부를 나타냅니다. 일반적으로 0.05보다 작으면 통계적으로 유의미하다고 판단합니다.
"""

import pandas as pd
import statsmodels.formula.api as smf
from sklearn.preprocessing import StandardScaler

# --- Code to define results_multi (copied from previously generated cell) ---
# 1. 두 학기 데이터프레임 결합 및 학기 지시자 추가
df_1_temp = df_1.copy()
df_2_temp = df_2.copy()

df_1_temp['학기'] = 1
df_2_temp['학기'] = 2

df_combined = pd.concat([df_1_temp, df_2_temp], ignore_index=True)

# 2. '학기_2' 더미 변수 생성 (1학기를 기준 학기로 설정)
df_combined['학기_2'] = (df_combined['학기'] == 2).astype(int)

# 3. '탐구질문 평균점수'와 '총괄평가' 표준화
scaler_mean_score = StandardScaler()
df_combined['탐구질문_평균점수_scaled'] = scaler_mean_score.fit_transform(df_combined[['탐구질문 평균점수']])

scaler_total_eval = StandardScaler()
df_combined['총괄평가_scaled'] = scaler_total_eval.fit_transform(df_combined[['총괄평가']])

# 4. 상호작용 항 생성: 표준화된 평균 점수와 학기 더미 변수
df_combined['상호작용_탐구질문_학기2'] = df_combined['탐구질문_평균점수_scaled'] * df_combined['학기_2']

# 5. 다중선형 회귀 모델 적합
formula = '총괄평가_scaled ~ 탐구질문_평균점수_scaled + 학기_2 + 상호작용_탐구질문_학기2'

model_multi = smf.ols(formula=formula, data=df_combined)
results_multi = model_multi.fit()
# --- End of code to define results_multi ---


print("\n--- 1학기 단일 회귀 모델의 표준화 계수 ---")
print(results.params['탐구질문 평균점수'])

print("\n--- 2학기 단일 회귀 모델의 표준화 계수 ---")
print(results_2.params['탐구질문 평균점수'])

print("\n--- 종합 다중선형 회귀 모델의 표준화 계수 ---")
print("1학기 '탐구질문 평균점수' 효과 (기준):", results_multi.params['탐구질문_평균점수_scaled'])
print("2학기 '탐구질문 평균점수' 영향력 변화 (상호작용):", results_multi.params['상호작용_탐구질문_학기2'])
print("2학기 '탐구질문 평균점수' 총 효과 (1학기 효과 + 변화):", results_multi.params['탐구질문_평균점수_scaled'] + results_multi.params['상호작용_탐구질문_학기2'])
print("2학기 효과 (탐구질문 평균점수 0일 때):", results_multi.params['학기_2'])

import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import seaborn as sns
import numpy as np

# 한글 폰트 설정 재확인 및 캐시 재구성
!sudo apt-get install -y fonts-nanum > /dev/null # 폰트 재설치 (출력 억제)
!sudo fc-cache -fv > /dev/null # 시스템 폰트 캐시 재구성 (출력 억제)
!rm -rf ~/.cache/matplotlib # Matplotlib 폰트 캐시 삭제
# fm._rebuild() # Matplotlib 폰트 캐시 강제 재구축 (이 함수는 현재 버전에서 사용되지 않음)

# Matplotlib 폰트 설정
plt.rcParams['font.family'] = 'NanumGothic'
plt.rcParams['axes.unicode_minus'] = False # 마이너스 부호 깨짐 방지

# 플롯 생성
plt.figure(figsize=(10, 7))

# 1학기 데이터 산점도
sns.scatterplot(x=df_1['탐구질문 평균점수'], y=df_1['총괄평가'], label='1학기 데이터', alpha=0.6, color='skyblue')

# 2학기 데이터 산점도
sns.scatterplot(x=df_2['탐구질문 평균점수'], y=df_2['총괄평가'], label='2학기 데이터', alpha=0.6, color='lightcoral')

# 1학기 회귀선 계산 및 플롯
# 표준화된 계수를 원본 스케일로 변환
coef_scaled_1 = results.params['탐구질문 평균점수']
mean_y_1 = df_1['총괄평가'].mean()
std_y_1 = df_1['총괄평가'].std()
mean_x_1 = df_1['탐구질문 평균점수'].mean()
std_x_1 = df_1['탐구질문 평균점수'].std()

slope_original_1 = coef_scaled_1 * (std_y_1 / std_x_1)
intercept_original_1 = mean_y_1 - slope_original_1 * mean_x_1

x_vals = np.array([df_combined['탐구질문 평균점수'].min(), df_combined['탐구질문 평균점수'].max()])
y_pred_line_1 = intercept_original_1 + slope_original_1 * x_vals
plt.plot(x_vals, y_pred_line_1, color='blue', linestyle='--', linewidth=2, label='1학기 회귀선')

# 2학기 회귀선 계산 및 플롯
# 표준화된 계수를 원본 스케일로 변환
coef_scaled_2 = results_2.params['탐구질문 평균점수']
mean_y_2 = df_2['총괄평가'].mean()
std_y_2 = df_2['총괄평가'].std()
mean_x_2 = df_2['탐구질문 평균점수'].mean()
std_x_2 = df_2['탐구질문 평균점수'].std()

slope_original_2 = coef_scaled_2 * (std_y_2 / std_x_2)
intercept_original_2 = mean_y_2 - slope_original_2 * mean_x_2

y_pred_line_2 = intercept_original_2 + slope_original_2 * x_vals
plt.plot(x_vals, y_pred_line_2, color='red', linestyle='--', linewidth=2, label='2학기 회귀선')

plt.title('1학기 vs 2학기 탐구질문 평균점수와 총괄평가 회귀선 비교')
plt.xlabel('탐구질문 평균점수')
plt.ylabel('총괄평가')
plt.legend()
plt.grid(True, linestyle=':', alpha=0.7)
plt.show()

from scipy import stats

# 1학기와 2학기의 총괄평가 점수 추출
total_eval_1st_semester = df_1['총괄평가']
total_eval_2nd_semester = df_2['총괄평가']

# 독립표본 T-검정 수행
t_statistic, p_value = stats.ttest_ind(total_eval_1st_semester, total_eval_2nd_semester)

print(f"\n--- 총괄평가 독립표본 T-검정 결과 ---")
print(f"T-통계량: {t_statistic:.3f}")
print(f"P-값: {p_value:.3f}")

# 결과 해석
alpha = 0.05 # 유의수준 설정
if p_value < alpha:
    print(f"P-값 ({p_value:.3f})은 유의수준 ({alpha})보다 작으므로, 귀무가설을 기각합니다.")
    print("이는 1학기와 2학기의 총괄평가 평균 점수 간에 통계적으로 유의미한 차이가 있음을 의미합니다.")
else:
    print(f"P-값 ({p_value:.3f})은 유의수준 ({alpha})보다 크므로, 귀무가설을 기각할 수 없습니다.")
    print("이는 1학기와 2학기의 총괄평가 평균 점수 간에 통계적으로 유의미한 차이가 없음을 의미합니다.")

# 각 학기 평균 출력 (참고용)
print(f"\n1학기 총괄평가 평균: {total_eval_1st_semester.mean():.3f}")
print(f"2학기 총괄평가 평균: {total_eval_2nd_semester.mean():.3f}")

"""### 총괄평가 독립표본 T-검정 결과 설명

위 T-검정 결과는 1학기와 2학기의 '총괄평가' 점수 평균에 통계적으로 유의미한 차이가 있는지 여부를 알려줍니다.

*   **T-통계량 (T-statistic):** 두 그룹의 평균 차이를 표준 오차로 나눈 값입니다. 이 값의 절대값이 클수록 두 그룹 간의 차이가 크다고 볼 수 있습니다.
*   **P-값 (P-value):** 귀무가설(두 학기의 총괄평가 평균에는 차이가 없다)이 옳다고 가정했을 때, 현재 관찰된 평균 차이 또는 그보다 극단적인 차이가 나타날 확률입니다. 일반적으로 P-값이 0.05보다 작으면 통계적으로 유의미한 차이가 있다고 판단합니다.

**해석:**
*   만약 **P-값이 0.05 미만**이라면, 1학기와 2학기의 '총괄평가' 평균 점수에는 **통계적으로 유의미한 차이**가 있다고 결론 내릴 수 있습니다. 이는 학기별로 학생들의 총괄평가가 달라졌을 가능성이 높다는 것을 의미합니다.
*   만약 **P-값이 0.05 이상**이라면, 1학기와 2학기의 '총괄평가' 평균 점수에는 **통계적으로 유의미한 차이가 있다고 보기 어렵다**고 결론 내릴 수 있습니다. 이는 관찰된 차이가 우연에 의한 것일 수 있음을 의미합니다.

### 종합 분석 및 가설 검증 요약

지금까지의 분석 결과를 바탕으로 '탐구질문 생성능력이 성적 향상에 영향력을 더 주었는가?'라는 사용자님의 가설을 검증하고, 관찰된 두 가지 주요 현상(총괄평가 점수 하락과 탐구질문 영향력 증가)을 종합적으로 설명합니다.

1.  **총괄평가 점수의 전반적인 하락 (독립표본 T-검정 결과):**
    *   1학기 총괄평균: 4.417점
    *   2학기 총괄평균: 3.827점
    *   독립표본 T-검정 결과(P-값 0.004)는 1학기와 2학기 총괄평가 평균 사이에 통계적으로 유의미한 차이가 있음을 보여줍니다. 즉, **2학기의 총괄평가 점수가 1학기보다 전반적으로 낮아졌습니다.** 이는 학기별 평가 기준, 학습 난이도, 또는 학생들의 전반적인 학습 태도 변화 등 다양한 요인에 기인할 수 있습니다.

2.  **탐구질문 생성능력의 영향력 증가 (종합 다중선형 회귀 분석 결과):**
    *   **1학기 '탐구질문 평균점수'의 영향력 (기준):** 0.4063
    *   **2학기 '탐구질문 평균점수'의 영향력 변화 (상호작용 항):** 0.1752 (유의미)
    *   **2학기 '탐구질문 평균점수'의 총 영향력:** 0.5816
    *   다중선형 회귀 분석 결과에서 **'학기'와 '탐구질문 평균점수' 간의 상호작용 항이 통계적으로 유의미한 양수 값(0.1752)을 가지는 것**이 핵심입니다. 이는 1학기에 비해 **2학기에 '탐구질문 평균점수'가 '총괄평가'에 미치는 '영향력' 또는 '설명력'이 유의미하게 증가했음**을 의미합니다.

3.  **두 현상에 대한 종합적인 해석 및 가설 검증:**
    *   **겉보기의 모순:** 총괄평가 점수 자체는 2학기에 하락했지만, 탐구질문 생성능력이 총괄평가에 미치는 영향력은 오히려 커졌습니다. 이는 모순이 아니라, **'절대적인 점수의 변화'**와 **'어떤 요인의 중요도(영향력) 변화'**는 다를 수 있음을 시사합니다.
    *   **비유:** 전체 학생들의 시험 점수 평균이 떨어지는 어려운 시험 상황에서도, 특정 학습 능력(예: 문제 해결 능력)이 높은 학생이 더 좋은 점수를 얻고, 그 능력의 차이가 점수 차이에 미치는 영향은 더 커질 수 있습니다. 즉, 어려운 환경일수록 해당 능력의 변별력이 더욱 중요해지는 것입니다.
    *   **가설 검증:** 사용자님의 가설이 '탐구질문 생성능력이 성적 **향상에 영향력을 더 주었는가?**'에 초점을 맞춘다면, 저희 분석 결과는 이 가설을 **강력하게 지지합니다.** 비록 총괄평가 점수대가 전반적으로 낮아졌을지라도, 2학기에는 '탐구질문 생성능력'이 학생들의 '총괄평가'를 설명하고 예측하는 데 있어 **더욱 중요한 변별 요인으로 작용했음**을 회귀 분석 결과가 명확히 보여주고 있습니다.
"""